export const attachment = Symbol("ATTACHMENT");
export const image = Symbol("IMAGE");
export const key = Symbol("KEY");
export const listLayout = Symbol("LIST_LAYOUT");
export const person = Symbol("PERSON");
export const search = Symbol("SEARCH");
export const settings = Symbol("SETTINGS");
export const trashcan = Symbol("TRASHCAN");
export const newspaper = Symbol("NEWSPAPER");
export const twitter = Symbol("TWITTER");
export const facebook = Symbol("FACEBOOK");
export const linkedin = Symbol("LINKEDIN");
export const sun = Symbol("SUN");
export const moon = Symbol("MOON");
export const check = Symbol("CHECK");
export const circle = Symbol("CIRCLE");
export const anterior = Symbol("ANTERIOR");
export const siguiente = Symbol("SIGUIENTE");
export const guardar = Symbol("GUARDAR");
export const cerrar = Symbol("CLOSE");
export const casa = Symbol("CASA");
export const imprimir = Symbol("PRINT");
export const agnadir = Symbol("AGNADIR");
export const reporte = Symbol("REPORTE");
export const edit = Symbol("EDIT");
export const cross = Symbol("CROSS");
export const door = Symbol("DOOR");

export const CATALOG = {
    [attachment]: () => import("$cmp/icons/Attachment.svelte"),
    [image]: () => import("$cmp/icons/Image.svelte"),
    [key]: () => import("$cmp/icons/Key.svelte"),
    [listLayout]: () => import("$cmp/icons/ListLayout.svelte"),
    [person]: () => import("$cmp/icons/Person.svelte"),
    [search]: () => import("$cmp/icons/Search.svelte"),
    [settings]: () => import("$cmp/icons/Settings.svelte"),
    [trashcan]: () => import("$cmp/icons/Trashcan.svelte"),
    [newspaper]: () => import("$cmp/icons/Article.svelte"),
    [twitter]: () => import("$cmp/icons/Twitter.svelte"),
    [facebook]: () => import("$cmp/icons/Facebook.svelte"),
    [linkedin]: () => import("$cmp/icons/LinkedIn.svelte"),
    [sun]: () => import("$cmp/icons/Sun.svelte"),
    [moon]: () => import("$cmp/icons/Moon.svelte"),
    [check]: () => import("$cmp/icons/Check.svelte"),
    [circle]: () => import("$cmp/icons/Circle.svelte"),
    [siguiente]: () => import("$cmp/icons/StepForward.svelte"),
    [guardar]: () => import("$cmp/icons/Save.svelte"),
    [anterior]: () => import("$cmp/icons/SkipBack.svelte"),
    [cerrar]: () => import("$cmp/icons/Close.svelte"),
    [casa]: () => import("$cmp/icons/Home.svelte"),
    [imprimir]: () => import("$cmp/icons/Print.svelte"),
    [agnadir]: () => import("$cmp/icons/Add.svelte"),
    [reporte]: () => import("$cmp/icons/Clipboard.svelte"),
    [edit]: () => import("$cmp/icons/Edit.svelte"),
    [cross]: () => import("$cmp/icons/Cross.svelte"),
    [door]: () => import("$cmp/icons/Door.svelte"),
} as const;

export type IconList = keyof typeof CATALOG;
